name: running_log
description: A simple running log.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  path: ^1.8.3
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  xml: ^6.5.0
  polyline_codec: ^0.1.6
  google_fonts: ^6.2.1
  flutter_native_splash: ^2.3.10
  flex_color_picker: ^3.4.0
  tinycolor2: ^3.0.1
  intl: ^0.19.0
  syncfusion_flutter_charts: ^26.2.9
  syncfusion_flutter_gauges: ^26.2.9
  envied: ^0.5.4+1
  json_annotation: ^4.8.1
  envied_generator: ^0.5.4+1
  file_picker: ^8.0.0+1
  http: ^1.2.0
  flutter_image_compress: ^2.3.0
  flutter_share: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/