name: running_log
description: A simple running log.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  path: ^1.8.3
  path_provider: ^2.1.2
  sqflite: ^2.3.2
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  xml: ^6.5.0
  polyline_codec: ^0.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/